services:
  - type: web
    name: vue-ssr-jod
    env: node
    buildCommand: yarn install && yarn build:client
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 22.x
    healthCheckPath: /healthz
